### PR TITLE
Added Nanobox guides and docs

### PR DESCRIPTION
**Pull request by sdomino**
Sorry about my linter cleaning up some hanging whitespace.

### CODE REVIEW

**Comment by sdomino** [comment]
Any needed changes or feedback before this can be merged?

**Comment by sdomino** [comment]
bump

**Comment by King-of-Spades** [comment]
Hi, I wanted to merge this to my `reborn` fork: https://github.com/King-of-Spades/beautiful-docs-reborn

Sadly, the guides are unreachable, and Nanobox in google has the subtext:

> WARNING: Nanobox is reaching its end of life on March 31, 2021. After that time, you will be unable to access the Nanobox service.

**Review by matheusfelipeog — COMMENTED** [review]
Thanks for your contribution @sdomino ;)

Apparently this project has been dead for a while, as mentioned above. I will close the PR because of this.

**Pull request closed without merging**
